package com.demo.hibernate.beans;
// Generated 2016-4-24 22:36:56 by Hibernate Tools 3.5.0.Final

/**
 * Address generated by hbm2java
 */
public class Address{

	private Integer id;
	private String username;
	private String name;
	private String sex;
	private String mobile;
	private String email;
	private String qq;
	private String company;
	private String address;
	private String postcode;

	public Address() {
	}

	public Address(String username, String name) {
		this.username = username;
		this.name = name;
	}

	public Address(String username, String name, String sex, String mobile, String email, String qq, String company,
			String address, String postcode) {
		this.username = username;
		this.name = name;
		this.sex = sex;
		this.mobile = mobile;
		this.email = email;
		this.qq = qq;
		this.company = company;
		this.address = address;
		this.postcode = postcode;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

}
