package com.demo.hibernate.beans;
// Generated 2016-4-24 22:36:56 by Hibernate Tools 3.5.0.Final

/**
 * Meeting generated by hbm2java
 */
public class Meeting{

	private Integer id;
	private String sender;
	private String starttime;
	private String endtime;
	private String address;
	private String title;
	private String content;

	public Meeting() {
	}

	public Meeting(String sender) {
		this.sender = sender;
	}

	public Meeting(String sender, String starttime, String endtime, String address, String title, String content) {
		this.sender = sender;
		this.starttime = starttime;
		this.endtime = endtime;
		this.address = address;
		this.title = title;
		this.content = content;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	public String getStarttime() {
		return this.starttime;
	}

	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	public String getEndtime() {
		return this.endtime;
	}

	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
