package com.demo.hibernate.beans;
// Generated 2016-4-24 22:36:56 by Hibernate Tools 3.5.0.Final

/**
 * Notice generated by hbm2java
 */
public class Notice{

	private Integer id;
	private String sender;
	private String title;
	private String content;
	private String sendtime;

	public Notice() {
	}

	public Notice(String sender) {
		this.sender = sender;
	}

	public Notice(String sender, String title, String content, String sendtime) {
		this.sender = sender;
		this.title = title;
		this.content = content;
		this.sendtime = sendtime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getSendtime() {
		return this.sendtime;
	}

	public void setSendtime(String sendtime) {
		this.sendtime = sendtime;
	}

}
