package com.demo.hibernate.beans;
// Generated 2016-4-24 22:36:56 by Hibernate Tools 3.5.0.Final

/**
 * Worklog generated by hbm2java
 */
public class Worklog{

	private Integer id;
	private String username;
	private Integer year;
	private Integer month;
	private Integer day;
	private String title;
	private String description;
	private String logtime;

	public Worklog() {
	}

	public Worklog(String username) {
		this.username = username;
	}

	public Worklog(String username, Integer year, Integer month, Integer day, String title, String description,
			String logtime) {
		this.username = username;
		this.year = year;
		this.month = month;
		this.day = day;
		this.title = title;
		this.description = description;
		this.logtime = logtime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public Integer getMonth() {
		return this.month;
	}

	public void setMonth(Integer month) {
		this.month = month;
	}

	public Integer getDay() {
		return this.day;
	}

	public void setDay(Integer day) {
		this.day = day;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLogtime() {
		return this.logtime;
	}

	public void setLogtime(String logtime) {
		this.logtime = logtime;
	}

}
